### ISSUE TITLE
Plugin doesn't load

### ISSUE THREAD

**Issue by Josje92** [Rickth64/homebridge-mhacwifi1#1]
The plugin doesn't load in Homebridge.

It says it received a syntax error..

```
[6/9/2020, 9:36:06 AM] ====================
[6/9/2020, 9:36:06 AM] ERROR LOADING PLUGIN homebridge-mhacwifi1:
[6/9/2020, 9:36:06 AM] /usr/local/lib/node_modules/homebridge-mhacwifi1/acwm-api/acwm-api.js:30
    wait = ms => new Promise(r => setTimeout(r, ms));
         ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-mhacwifi1/index.js:25:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[6/9/2020, 9:36:06 AM] ====================
```

**Comment by TeunVR** [comment]
Make sure you use a newer nodejs version.
Don't know the exact version, but i think your version is out of date.

**Comment by Josje92** [comment]
Hi Teun,

I'm on Node v10, but see that there is a v12 available now.
Haven't checked that.

However, I changed a few lines in acwm-api/acwm-api.js which also fixed it for Node v10!

Line 30, changed from:
`wait = ms => new Promise(r => setTimeout(r, ms));`
to:
`wait(ms) { return new Promise(r => setTimeout(r, ms)) };`

Line 32, changed from:
`retryWriteCommandOperation = (cmd, data, delay, times) => new Promise((resolve, reject) => {`
to
`retryWriteCommandOperation(cmd, data, delay, times) { return new Promise((resolve, reject) => {`

Line 44, changed from:
`});`
to
`}) };`


You think this is worth a PR, or should we just say update to Node v12 is the solution?

**Comment by TeunVR** [comment]
I had the same problem and updated to a newer nodejs version.
But if a small change makes it work on more versions then that might be worth it :)

**Comment by Josje92** [comment]
[PR](https://github.com/Rickth64/homebridge-mhacwifi1/pull/2) made!
